"""
DarwinTrade backtest CLI.

Single-strategy harness for the bundled engine. LLM credentials come from
the project `.env` (LLM_BASE_URL / LLM_API_KEY / LLM_MODEL). There is no
`--llm-profile` switch — this entrypoint runs DarwinTrade and only
DarwinTrade.
"""
import argparse
import os
import re
import sys
from pathlib import Path
from typing import List, Optional

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(REPO_ROOT / ".env", override=False)
except Exception:
    pass

from backtest.stockbench.pipeline import run_backtest
from backtest.stockbench.strategies.darwintrade import DarwinTradeStrategy
from backtest.stockbench.utils.logging_setup import setup_json_logging, Metrics
from backtest.stockbench.reports import _default_run_id
from backtest.stockbench.core.data_hub import refresh_api_clients, set_data_mode

DEFAULT_CFG = REPO_ROOT / "backtest" / "stockbench" / "config_darwintrade.yaml"


def _build_strategy(name: str, config: dict):
    """Resolve the strategy class by name.

    Kept lazy so external agents' heavy imports (backtrader, faiss, etc.)
    only fire when actually needed.
    """
    key = (name or "darwintrade").strip().lower()
    if key in {"darwintrade", "darwin", "dt"}:
        return DarwinTradeStrategy(config)
    if key in {"finagent", "fin-agent", "fin_agent"}:
        from backtest.stockbench.strategies.external_llm_adapters import FinAgentStrategy
        strat = FinAgentStrategy(config)
        config.setdefault("strategy", {})["name"] = "finagent"
        return strat
    if key in {"tradingagents", "trading-agents", "trading_agents", "ta"}:
        from backtest.stockbench.strategies.tradingagents_baseline import Strategy as _TAStrategy
        strat = _TAStrategy(config)
        config.setdefault("strategy", {})["name"] = "tradingagents"
        return strat
    raise SystemExit(
        f"Unknown --strategy {name!r}. Valid: darwintrade | finagent | tradingagents"
    )


def _resolve_env_value(value: object) -> str:
    text = str(value or "")
    if text.startswith("${") and text.endswith("}"):
        return os.getenv(text[2:-1], "")
    return text


def _configure_resume(
    config: dict,
    effective_run_id: str,
    resume_enabled: bool,
    resume_summary: Optional[Path],
    resume_date: Optional[str],
) -> None:
    backtest_cfg = config.setdefault("backtest", {})
    resume_cfg = backtest_cfg.setdefault("resume", {})
    resume_cfg["enabled"] = bool(resume_enabled)
    if resume_summary is not None:
        resume_cfg["daily_summary_path"] = str(resume_summary)
        resume_cfg["enabled"] = True
    if resume_date:
        resume_cfg["trade_date"] = str(resume_date)

    if not bool(resume_cfg.get("enabled", False)):
        return

    summary_path_value = (
        resume_cfg.get("daily_summary_path")
        or resume_cfg.get("snapshot_path")
        or resume_cfg.get("path")
    )
    inferred = not bool(summary_path_value)
    if inferred:
        summary_path = (
            REPO_ROOT
            / "storage"
            / "reports"
            / "backtest"
            / effective_run_id
            / "daily_run_summary.jsonl"
        )
        resume_cfg["daily_summary_path"] = str(summary_path)
    else:
        summary_path = Path(str(summary_path_value))

    if summary_path.exists():
        print(f"Resume summary: {summary_path}")
        if str(resume_cfg.get("trade_date") or "").strip():
            print(f"Resume trade date: {resume_cfg['trade_date']}")
        return

    if inferred:
        resume_cfg["enabled"] = False
        print(f"Resume summary not found, starting fresh: {summary_path}")
        return

    raise SystemExit(f"Resume summary not found: {summary_path}")


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="backtest.stockbench.cli",
        description="Run a DarwinTrade backtest end-to-end.",
    )
    p.add_argument("--cfg", type=Path, default=DEFAULT_CFG, help="Configuration file path")
    p.add_argument("--start", default="2025-03-01", help="Start date (YYYY-MM-DD)")
    p.add_argument("--end", default="2025-07-31", help="End date (YYYY-MM-DD)")
    p.add_argument("--symbols", "-s", default="", help="Comma/space separated overrides for symbols_universe")
    p.add_argument("--run-id", default=None, help="Output run_id (auto-generated by default)")
    p.add_argument(
        "--strategy",
        default="darwintrade",
        help="darwintrade | finagent | tradingagents",
    )
    p.add_argument("--max-positions", type=int, default=None)
    p.add_argument("--cooldown-days", type=int, default=None)
    p.add_argument("--min-holding-days", type=int, default=None)
    p.add_argument("--summary-llm", action="store_true", help="Generate natural-language summary after backtest")

    bench = p.add_argument_group("benchmark")
    bench.add_argument("--benchmark-type", default=None,
                       help="symbol|basket|per_symbol_buy_and_hold")
    bench.add_argument("--benchmark-symbol", default=None)
    bench.add_argument("--benchmark-basket", default=None)
    bench.add_argument("--benchmark-field", default=None,
                       help="adjusted_close|close")
    bench.add_argument("--benchmark-rebalance", default=None,
                       help="daily|weekly|monthly|none")
    bench.add_argument("--benchmark-reindex", default=None,
                       help="inner_join|business")
    bench.add_argument("--benchmark-fill", default=None, help="ffill|none")
    bench.add_argument("--benchmark-fill-limit", type=int, default=None)
    bench.add_argument("--benchmark-total-cash", type=float, default=None)
    bench.add_argument("--benchmark-trade-price-field", default=None)
    bench.add_argument("--benchmark-daily-metrics", default=None,
                       help="comma-separated list, e.g., cum_return,max_drawdown,sortino")
    bench.add_argument("--benchmark-sortino-mode", default=None,
                       help="rolling|to_date")
    bench.add_argument("--benchmark-sortino-window", type=int, default=None)
    bench.add_argument("--benchmark-save-format", default=None,
                       help="comma-separated, e.g., text,image")

    data = p.add_argument_group("data")
    data.add_argument("--data-mode", default=None, help="auto|offline_only")
    data.add_argument("--offline", action="store_true", help="Shortcut for --data-mode offline_only")

    resume = p.add_argument_group("resume")
    resume_g = resume.add_mutually_exclusive_group()
    resume_g.add_argument("--resume", dest="resume", action="store_true", default=True)
    resume_g.add_argument("--no-resume", dest="resume", action="store_false")
    resume.add_argument("--resume-summary", type=Path, default=None,
                        help="Resume from a daily_run_summary.jsonl path")
    resume.add_argument("--resume-date", default=None,
                        help="Resume from a specific trade date (YYYY-MM-DD)")

    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = _build_parser().parse_args(argv)

    if not args.cfg.exists():
        raise SystemExit(f"Configuration file not found: {args.cfg}")

    with args.cfg.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}

    api_cfg = dict(config.get("api", {}) or {})
    polygon_cfg = dict(api_cfg.get("polygon", {}) or {})
    finnhub_cfg = dict(api_cfg.get("finnhub", {}) or {})
    polygon_key = _resolve_env_value(
        polygon_cfg.get("api_key") or os.getenv("POLYGON_API_KEY", "")
    )
    finnhub_key = _resolve_env_value(
        finnhub_cfg.get("api_key")
        or os.getenv("FINNUB_API_KEY", "")
        or os.getenv("FINNHUB_API_KEY", "")
    )
    if polygon_key:
        os.environ["POLYGON_API_KEY"] = polygon_key
    if finnhub_key:
        os.environ["FINNUB_API_KEY"] = finnhub_key
    refresh_api_clients(
        polygon_api_key=polygon_key or None,
        finnhub_api_key=finnhub_key or None,
    )

    setup_json_logging(config)

    data_cfg = config.setdefault("data", {})
    if args.offline:
        data_cfg["mode"] = "offline_only"
        set_data_mode("offline_only")
    elif args.data_mode:
        data_cfg["mode"] = str(args.data_mode)
        set_data_mode(str(args.data_mode))
    else:
        dm = data_cfg.get("mode")
        if dm:
            set_data_mode(str(dm))

    Metrics().incr("run_backtest.start", 1)

    sym_list: List[str] = []
    if args.symbols:
        sym_list = [s for s in re.split(r"[\s,]+", args.symbols.strip()) if s]
    if not sym_list:
        sym_list = list(config.get("symbols_universe", []))

    effective_run_id = args.run_id or _default_run_id()
    os.environ["TA_RUN_ID"] = effective_run_id

    _configure_resume(
        config, effective_run_id,
        args.resume, args.resume_summary, args.resume_date,
    )

    config.setdefault("strategy", {})["name"] = args.strategy

    if args.max_positions is not None:
        config.setdefault("risk", {})["max_positions"] = int(args.max_positions)
    if args.cooldown_days is not None:
        config.setdefault("risk", {})["cooldown_days"] = int(args.cooldown_days)
    if args.min_holding_days is not None:
        config.setdefault("risk", {})["min_holding_days"] = int(args.min_holding_days)
    if args.summary_llm:
        config.setdefault("backtest", {})["summary_llm"] = True
    config.setdefault("backtest", {})["timespan"] = "day"

    bench_cfg = config.setdefault("backtest", {}).setdefault("benchmark", {})
    if args.benchmark_type:
        bench_cfg["type"] = args.benchmark_type
    if args.benchmark_symbol:
        bench_cfg["symbol"] = args.benchmark_symbol
    if args.benchmark_basket:
        bench_cfg["basket"] = args.benchmark_basket
    if args.benchmark_field:
        bench_cfg["field"] = args.benchmark_field
    if args.benchmark_rebalance:
        bench_cfg["rebalance"] = args.benchmark_rebalance
    if args.benchmark_reindex:
        bench_cfg["reindex"] = args.benchmark_reindex
    if args.benchmark_fill:
        bench_cfg["fill"] = args.benchmark_fill
    if args.benchmark_fill_limit is not None:
        bench_cfg["fill_limit"] = int(args.benchmark_fill_limit)
    if args.benchmark_total_cash is not None:
        bench_cfg["total_cash"] = float(args.benchmark_total_cash)
    if args.benchmark_trade_price_field:
        bench_cfg["trade_price_field"] = args.benchmark_trade_price_field
    if args.benchmark_daily_metrics:
        bench_cfg["daily_metrics"] = [
            s.strip() for s in str(args.benchmark_daily_metrics).split(",") if s.strip()
        ]
    if args.benchmark_sortino_mode:
        bench_cfg["sortino_mode"] = args.benchmark_sortino_mode
    if args.benchmark_sortino_window is not None:
        bench_cfg["sortino_window"] = int(args.benchmark_sortino_window)
    if args.benchmark_save_format:
        bench_cfg["save_format"] = [
            s.strip() for s in str(args.benchmark_save_format).split(",") if s.strip()
        ]

    strat = _build_strategy(args.strategy, config)

    res = run_backtest(
        config, strat, args.start, args.end, sym_list,
        run_id=effective_run_id, timespan="day",
    )

    out_dir = res.get("output_dir") if isinstance(res, dict) else None
    if out_dir:
        print(f"Output directory: {out_dir}")
    if hasattr(strat, "on_end"):
        try:
            strat.on_end(None)
        except Exception as exc:
            print(f"[warn] {type(strat).__name__}.on_end raised: {exc}")
    if hasattr(strat, "artifact_root"):
        print(f"{args.strategy} summary: {Path(strat.artifact_root) / 'backtest_summary.json'}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
